USE [master]
GO

/****** Object:  Database [db_reminder]    Script Date: 3/26/2018 10:59:04 PM ******/
CREATE DATABASE [db_reminder]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'db_reminder', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL11.MSSQLSERVER\MSSQL\DATA\db_reminder.mdf' , SIZE = 3072KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'db_reminder_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL11.MSSQLSERVER\MSSQL\DATA\db_reminder_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [db_reminder] SET COMPATIBILITY_LEVEL = 110
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [db_reminder].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [db_reminder] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [db_reminder] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [db_reminder] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [db_reminder] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [db_reminder] SET ARITHABORT OFF 
GO

ALTER DATABASE [db_reminder] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [db_reminder] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [db_reminder] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [db_reminder] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [db_reminder] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [db_reminder] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [db_reminder] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [db_reminder] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [db_reminder] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [db_reminder] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [db_reminder] SET  DISABLE_BROKER 
GO

ALTER DATABASE [db_reminder] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [db_reminder] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [db_reminder] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [db_reminder] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [db_reminder] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [db_reminder] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [db_reminder] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [db_reminder] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [db_reminder] SET  MULTI_USER 
GO

ALTER DATABASE [db_reminder] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [db_reminder] SET DB_CHAINING OFF 
GO

ALTER DATABASE [db_reminder] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [db_reminder] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [db_reminder] SET  READ_WRITE 
GO


